  // File generated by FlutterFire CLI.
  // ignore_for_file: type=lint
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          return windows;
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBTUYXCZvsoD1VaYrluDYLZtQZzkEI1KsE',
      appId: '1:1060119988188:web:08466d22926c94b49c7119',
      messagingSenderId: '1060119988188',
      projectId: 'chatting-app-78c46',
      authDomain: 'chatting-app-78c46.firebaseapp.com',
      storageBucket: 'chatting-app-78c46.appspot.com',
      measurementId: 'G-N8YWZ5WTG0',
    );

    static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyD98oa6JV7moJn-ykNHrG8arheRO5JhNrY',
      appId: '1:1060119988188:android:40777b8069e9b98f9c7119',
      messagingSenderId: '1060119988188',
      projectId: 'chatting-app-78c46',
      storageBucket: 'chatting-app-78c46.appspot.com',
    );

    static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDaBwjdl1PyLmiRgF2ePv1jBo39fhs7gx8',
      appId: '1:1060119988188:ios:f04485f816bede7b9c7119',
      messagingSenderId: '1060119988188',
      projectId: 'chatting-app-78c46',
      storageBucket: 'chatting-app-78c46.appspot.com',
      iosBundleId: 'com.example.chattingAppDemo',
    );

    static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyDaBwjdl1PyLmiRgF2ePv1jBo39fhs7gx8',
      appId: '1:1060119988188:ios:f04485f816bede7b9c7119',
      messagingSenderId: '1060119988188',
      projectId: 'chatting-app-78c46',
      storageBucket: 'chatting-app-78c46.appspot.com',
      iosBundleId: 'com.example.chattingAppDemo',
    );

    static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyBTUYXCZvsoD1VaYrluDYLZtQZzkEI1KsE',
      appId: '1:1060119988188:web:4573ba4d1f1504d99c7119',
      messagingSenderId: '1060119988188',
      projectId: 'chatting-app-78c46',
      authDomain: 'chatting-app-78c46.firebaseapp.com',
      storageBucket: 'chatting-app-78c46.appspot.com',
      measurementId: 'G-7FSRJYM06F',
    );
  }
